# Generated by Django 4.2.6 on 2024-05-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='user',
            new_name='store_owner',
        ),
    ]
