# Generated by Django 4.2.6 on 2024-05-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_store_owner_store_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='user',
            new_name='user_id',
        ),
    ]
