# Generated by Django 4.2.6 on 2024-05-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_user_store_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='user_id',
            new_name='user',
        ),
    ]
